allowBuilds:
  esbuild: true
  sharp: false
catalog:
  vite: 'npm:@voidzero-dev/vite-plus-core@^0.2.1' # <-- Change @latest to @^0.2.1
  vite-plus: ^0.2.4
  vitest: 4.1.9
minimumReleaseAgeExclude:
  - svelte@5.56.5
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
