allowBuilds:
  esbuild: true
  sharp: false
catalog:
  vite: "npm:@voidzero-dev/vite-plus-core@^0.2.1" # <-- Change @latest to @^0.2.1
  vitest: 4.1.9
  vite-plus: ^0.2.1
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
